class TRIPULANTE{
    private string Nombre{get;set;}
    private int Telefono{get;set;}
    private int cedula{get;set;}
    private int Edad{get;set}
    private int Tiempo_en_la_empresa{get;set;}
    private string sexo{get;set;}
    private string barco{get;set;}

    public void{ string Nombre; int Telefono; int cedula; int Edad; int Tiempo_en_la_empresa; string sexo; string barco}


}